<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.4.0/bootbox.min.js"></script>
<script type="text/javascript" src="<?php echo $cfg['server_root_extra']; ?>/setupfolder/sys_param.js"></script>
<script type="text/javascript" src="<?php echo $cfg['server_root_extra']; ?>/js/main.js"></script>
<script type="text/javascript" src="<?php echo $cfg['server_root_extra']; ?>/mvc/js/change.password.js"></script>
<script type="text/javascript" src="<?php echo $cfg['server_root_extra']; ?>/js/jquery.base64.js"></script>